{#-
Below are imports for Bakery's macros. If any are unneeded, they can be removed.
Bakery handles bootstrapping the files into template rendering.
-#}
{%- import "apt.j2" as apt -%}
FROM docker.io/library/ubuntu:24.04 AS builder

ARG DEBIAN_FRONTEND=noninteractive

### Initialize PTI in container ###
{{ apt.run_setup() }}

# Download the RStudio Workbench session components
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN mkdir -p /pwb-staging && \
    curl -fsSL -o /pwb-staging/rsp-session-multi-linux.tar.gz "https://s3.amazonaws.com/rstudio-ide-build/session/multi/x86_64/rsp-session-multi-linux-{{ Image.Version | replace('+', '-') }}-x86_64.tar.gz" && \
    mkdir -p /opt/session-components && \
    tar -C /opt/session-components -xpf /pwb-staging/rsp-session-multi-linux.tar.gz && \
    chmod 755 /opt/session-components && \
    rm -rf /pwb-staging

# Create the final image
FROM docker.io/library/ubuntu:24.04 AS build
LABEL org.opencontainers.image.base.name="docker.io/library/ubuntu:24.04"

ARG DEBIAN_FRONTEND=noninteractive

{{ apt.run_update_upgrade() }}

# Copy session components and packaged session-init binary from the builder stage
COPY --from=builder --chmod=755 /opt/session-components /opt/session-components
COPY --from=builder --chmod=755 /opt/session-components/bin/session-init /usr/local/bin/entrypoint

CMD ["/usr/local/bin/entrypoint"]
