# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
        exclude: "^.*\\.sh\\.jinja2$"
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-yaml
        exclude: "^.*goss.yaml$"
    -   id: detect-aws-credentials
        args: [--allow-missing-credentials]
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
    -   id: no-commit-to-branch
        args: [--branch, main]
    -   id: pretty-format-json
        exclude: "^\\.claude/settings\\.json$"
    -   id: trailing-whitespace
-   repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
    -   id: shellcheck
        args: ["-s", "bash"]
        exclude: "wait-for-it\\.sh$"
-   repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
    -   id: actionlint
