#######################################################################################################################
# BAKERY CONFIG
#######################################################################################################################

[[registry]]
host = "docker.io"
namespace = "posit"

[repository]
url = "github.com/rstudio/proto-posit-images-workbench"
vendor = "Posit Software, PBC"
maintainer = "docker@posit.co"
authors = [
    "Ian H. Pittwood <ian.pittwood@posit.co>"
]
