FROM docker.io/library/ubuntu:24.04 AS builder

ARG DEBIAN_FRONTEND=noninteractive
ARG BUILDARCH
ARG TARGETARCH=${BUILDARCH}

SHELL ["/bin/bash", "-euo", "pipefail", "-c"]

### Setup environment ###
RUN echo 'Acquire::Retries "3"; Acquire::http::Timeout "30"; Acquire::https::Timeout "30";' > /etc/apt/apt.conf.d/99-retries && \
    apt-get update -yqq --fix-missing && \
    apt-get upgrade -yqq && \
    apt-get dist-upgrade -yqq && \
    apt-get autoremove -yqq --purge && \
    apt-get install -yqq --no-install-recommends \
        curl \
        ca-certificates \
        gnupg \
        tar && \
    apt-get install -yqq --no-install-recommends locales && \
    localedef -i en_US -f UTF-8 en_US.UTF-8 && \
    bash -c "$(curl -1fsSL 'https://dl.posit.co/public/pro/setup.deb.sh')" && \
    apt-get clean -yqq && \
    rm -rf /var/lib/apt/lists/*
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

# Download the RStudio Workbench session components
RUN case ${TARGETARCH} in \
      amd64) CDN_ARCH=x86_64 ;; \
      arm64) CDN_ARCH=arm64 ;; \
      *) echo "Unsupported architecture: ${TARGETARCH}" && exit 1 ;; \
    esac && \
    mkdir -p /pwb-staging && \
    curl -fsSL -o /pwb-staging/rsp-session-multi-linux.tar.gz "https://s3.amazonaws.com/rstudio-ide-build/session/multi/$CDN_ARCH/rsp-session-multi-linux-2026.08.2-200.pro1-$CDN_ARCH.tar.gz" && \
    mkdir -p /opt/session-components && \
    tar -C /opt/session-components -xpf /pwb-staging/rsp-session-multi-linux.tar.gz && \
    chmod -R a+rX /opt/session-components && \
    rm -rf /pwb-staging

FROM docker.io/library/ubuntu:24.04
LABEL org.opencontainers.image.base.name="docker.io/library/ubuntu:24.04"
COPY --from=builder /opt/session-components /opt/session-components
CMD ["/opt/session-components/bin/session-init"]
