ARG REGISTRY=docker.io
{% if not is_minimal -%}
ARG PYTHON_VERSION="{{ python_version }}"
ARG R_VERSION="{{ r_version }}"
FROM ${REGISTRY}/posit/base:ubuntu2204
{%- else -%}
FROM ${REGISTRY}/posit/base:ubuntu2204-min
{%- endif %}

### ARG declarations ###
ARG DEBIAN_FRONTEND=noninteractive
ARG SCRIPTS_DIR=/opt/positscripts
{%- if not is_minimal %}
ARG PYTHON_VERSION="{{ python_version }}"
ARG R_VERSION="{{ r_version }}"
{%- endif %}
ARG WORKBENCH_VERSION="{{ workbench_version }}"
ARG RSTUDIO_INSTALL_NO_LICENSE_INITIALIZATION=1

ENV STARTUP_DEBUG_MODE 0
ENV RSW_LICENSE ""
ENV RSW_LICENSE_SERVER ""
ENV RSW_TESTUSER rstudio
ENV RSW_TESTUSER_PASSWD rstudio
ENV RSW_TESTUSER_UID 10000
ENV RSW_LAUNCHER true
ENV RSW_LAUNCHER_TIMEOUT 10
ENV DIAGNOSTIC_DIR /var/log/rstudio
ENV DIAGNOSTIC_ENABLE false
ENV DIAGNOSTIC_ONLY false

### Install System Packages ###
COPY common/ubuntu/22.04/packages.txt /tmp/packages.txt
{% if not is_minimal -%}
COPY common/ubuntu/22.04/optional_packages.txt /tmp/optional_packages.txt
{%- endif %}
RUN $SCRIPTS_DIR/apt.sh --update upgrade \
    && $SCRIPTS_DIR/apt.sh install $(cat /tmp/packages.txt) \
    && rm -f /tmp/packages.txt \
    {%- if not is_minimal %}
    && $SCRIPTS_DIR/apt.sh install $(cat /tmp/optional_packages.txt) \
    && rm -f /tmp/optional_packages.txt \
    {%- endif %}
    && $SCRIPTS_DIR/apt.sh --clean

### Install Workbench {{ workbench_version }} ###
COPY common/ubuntu/scripts/install_workbench.sh /tmp/install_workbench.sh
RUN OS_URL=jammy /tmp/install_workbench.sh

### Install Quarto to PATH ###
RUN ln -s /lib/rstudio-server/bin/quarto/bin/quarto /usr/local/bin/quarto

{% if not is_minimal -%}
### Install TinyTeX using Quarto ###
RUN $SCRIPTS_DIR/install_quarto.sh --install-tinytex --add-path-tinytex

### Install Jupyter and extensions ###
RUN $SCRIPTS_DIR/install_python.sh --install-jupyter --install-jupyter-kernel -- ${PYTHON_VERSION}
{%- endif %}

### Copy startup scripts ###
COPY --chmod=0775 {{ rel_path }}/scripts/startup.sh /usr/local/bin/startup.sh
COPY {{ rel_path }}/startup/launcher /startup/launcher
COPY {{ rel_path }}/startup/base /startup/base
COPY {{ rel_path }}/startup/supervisord.conf /etc/supervisor/supervisord.conf
{%- if not is_minimal %}
COPY {{ rel_path }}/startup/user-provisioning /startup/user-provisioning
COPY --chmod=600 {{ rel_path }}/conf/sssd/sssd.conf /etc/sssd/sssd.conf
{%- endif %}
COPY {{ rel_path }}/conf/rstudio /etc/rstudio

### Configure Workbench ###
RUN mkdir -p /var/lib/rstudio-server/monitor/log \
    && chown -R rstudio-server:rstudio-server /var/lib/rstudio-server/monitor \
    && mkdir -p /startup/custom/ \
    && printf '\n# allow home directory creation\nsession required pam_mkhomedir.so skel=/etc/skel umask=0027\n' >> /etc/pam.d/common-session \
    && echo "RSPM=https://packagemanager.posit.co/cran/__linux__/jammy/latest" > /etc/rstudio/repos.conf \
    && echo "CRAN=https://packagemanager.posit.co/cran/__linux__/jammy/latest" >> /etc/rstudio/repos.conf

EXPOSE 8787/tcp
EXPOSE 5559/tcp
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
