name: Development
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Product version to build (e.g. 2026.01.2+418.pro1)"
        required: false
        type: string
      stream:
        description: "Dev stream to build (e.g. 'daily')"
        required: false
        type: string

  schedule:
    # Hourly rebuild of dev images
    - cron: "45 4 * * *" # At 04:45 every day

  pull_request:

  push:
    branches:
      - main

concurrency:
  # Only cancel in-progress runs for pull_request events, this prevents cancelling workflows against main or tags
  # A pull_request will reuse the same group thus enabling cancelation, all others receive a unique run_id
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    # This should be the only action checked as required in the repo settings.
    #
    # This is a meta-job, here to express the conditions we require
    # in order to consider a CI run to be successful.
    if: always()

    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - dev

    steps:
      - uses: re-actors/alls-green@release/v1
        id: alls-green
        with:
          jobs: ${{ toJSON(needs) }}
      - if: always() && github.ref == 'refs/heads/main'
        continue-on-error: true
        uses: posit-dev/images-shared/.github/actions/slack-build-notify@main
        with:
          result: ${{ steps.alls-green.outcome }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}

  dev:
    name: Dev Build
    # Dev Build
    #
    # Builds all development versions of each image in parallel.
    #
    # Run on merges to main, or on hourly scheduled re-builds.
    permissions:
      contents: read
      packages: write

    uses: "posit-dev/images-shared/.github/workflows/bakery-build-native.yml@main"
    with:
      dev-versions: "only"
      matrix-versions: "exclude"
      image-version: ${{ inputs.version }}
      dev-stream: ${{ inputs.stream }}
      # Push on merges to main, scheduled rebuilds, and dispatches targeting main.
      push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' }}

  clean:
    name: Clean
    if: always() && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    needs:
      - dev

    uses: "posit-dev/images-shared/.github/workflows/clean.yml@main"
    with:
      dev-versions: "only"
      remove-dangling-caches: true
      remove-caches-older-than: 14
      clean-temporary-images: false