name: Issue Automation
on:
  issues:
    types:
      - opened

permissions: {}

jobs:
  issue:
    # only run in posit-dev/images-workbench.
    if: github.repository == 'posit-dev/images-workbench'
    runs-on: ubuntu-latest
    permissions: {}
    steps:

      - name: GitHub App Token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1  # v3.2.0
        id: app-token
        with:
          client-id: ${{ secrets.WORKBENCH_IDE_RELEASE_CLIENT_ID }}
          private-key: ${{ secrets.WORKBENCH_IDE_RELEASE_PEM }}

      - name: Add to Platform Carbon Project
        uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd  # v2.0.0
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          project-url: https://github.com/orgs/posit-dev/projects/17

      - name: Add Default Labels
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          GH_REPO: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: gh issue edit "$ISSUE_NUMBER" --add-label "docker"
