name: Session Images
on:
  schedule:
    # Weekly rebuild of all images, to pick up any upstream changes.
    - cron: "15 4 * * 0" # At 04:15 on Sunday

  push:
    branches:
      - main

permissions: {}

concurrency:
  # Only cancel in-progress runs for pull_request events, this prevents cancelling workflows against main or tags
  # A pull_request will reuse the same group thus enabling cancelation, all others receive a unique run_id
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    if: always()
    runs-on: ubuntu-latest
    permissions: {}
    timeout-minutes: 10
    needs:
      - build
    steps:
      - uses: re-actors/alls-green@release/v1
        id: alls-green
        with:
          jobs: ${{ toJSON(needs) }}
          allowed-skips: clean
      - if: always() && github.ref == 'refs/heads/main'
        continue-on-error: true
        uses: posit-dev/images-shared/.github/actions/slack-build-notify@main
        with:
          result: ${{ steps.alls-green.outcome }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}

  build:
    name: Build
    # Build all images, excluding dev versions.
    #
    # Builds all versions of each image in parallel.
    #
    # Run on merges to main, or on weekly scheduled re-builds.
    if: github.event_name == 'push' || github.event_name == 'schedule'
    permissions:
      contents: read
      packages: write

    uses: "posit-dev/images-shared/.github/workflows/bakery-build-native.yml@main"
    secrets:
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      DOCKER_HUB_README_USERNAME: ${{ secrets.DOCKER_HUB_README_USERNAME }}
      DOCKER_HUB_README_PASSWORD: ${{ secrets.DOCKER_HUB_README_PASSWORD }}
    with:
      matrix-versions: only
      # Push images only for merges into main and weekly schduled re-builds.
      push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'schedule' }}

  clean:
    name: Clean
    if: always() && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    needs:
      - build

    uses: "posit-dev/images-shared/.github/workflows/clean.yml@main"
    with:
      matrix-versions: "only"
      remove-dangling-caches: true
      remove-caches-older-than: 14
      remove-dangling-temporary-images: false
      remove-temporary-images-older-than: 3
